development:
  secret_key_base: 9cc85c7243b02fda10126ea0d989daab4669b38ce7b764662c48a5b97761d51a14c8c3aea7963f59cdcffd5f3ab8bba1d292d743089aa870f0bc6b7c641b996d
  mail_username: 7495500@gmail.com
  mail_password: ktotI1987
